# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0002_auto_20170926_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='Moviec',
        ),
    ]
